feat: todo data CURD API
EveryAnalytics-Study/todo-list pull request #8
Opened 2021-09-08 18:04 UTC by SenseCodeValue

## Description

todo를 Localstorage에서 CRUD 하기 위한 API개발 완료

## Help Wanted 👀

## Related Issues

resolve #
fix #7 

## Checklist ✋

- [x] PR 타이틀을 `{PR type}: {PR title}`로 맞췄습니다. (type 예시: feat | fix | BREAKING CHANGE | chore | ci | docs | style | refactor | perf | test) (참고: [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/))
- [x] 모든 **변경점**들을 확인했으며 적절히 설명했습니다.
- [x] 빌드와 테스트가 정상적으로 수행됨을 확인했습니다. (`npm run build`, `npm run test`)
- [x] 깃헙 이슈를 연결하겠습니다. (커밋에 resolve #이슈넘버 적거나 PR생성 후 Linked Issue 추가)

2021-09-09 07:34 UTC, MiryangJung commented on src/test/api/todo.test.ts
> +    const todo = createTodo('정대윤');
테스트에 facker를 도입해보는건어떤가요?ㅎㅎ

2021-09-09 09:47 UTC, SenseCodeValue commented on src/test/api/todo.test.ts
> +    const todo = createTodo('정대윤');
오 그것도 좋은 생각이네용!

2021-09-09 17:28 UTC, hy57in approved these changes
수고하셨습니당!

2021-09-09 17:28 UTC, hy57in commented on src/api/todo.ts
> +};
오호 굳굳!

2021-09-09 17:28 UTC, hy57in commented on src/api/todo.ts
> +};
여긴 `console.info` 없나요?ㅎㅎ

2021-09-09 17:28 UTC, hy57in commented on src/test/api/todo.test.ts
> +    const todo = createTodo('정대윤');
오 그 더미데이터 생성해주는 faker 말씀하시는건가요?

2021-09-10 02:23 UTC, Leehaeun0 requested changes

2021-09-10 02:23 UTC, Leehaeun0 commented on src/api/todo.ts
> +  return todos.map(todo => {
todo 라는 파라미터의 값을 직접적으로 변환하는 건 별로 좋은 패턴이 아니라고 알고 있어요. ([이 페이지](https://wikidocs.net/605)나 'remove assignments to parameters' 로 검색하면 관련 글을 볼 수 있습니다.)

`temp = todo;` 이런식으로 변수를 쪼개서 temp 라는 변수의 값을 사용하셔도 좋고, 참고만 하셔도 좋은데 저는 주로 아래와 같이 씁니다. 혹은 if 문을 삼항연산자로 바꿔서 쓰기도 합니다.

```suggestion
  return todos.map(todo => {
    if (todo.id !== id) return todo;
    return {
      ...todo,
      completed,
      updateDatetime: new Date().toString(),
      completedDatetime: completed ?? new Date().toString(),
    }
  })
```

2021-09-10 02:24 UTC, Leehaeun0 approved these changes

2021-09-10 07:30 UTC, SenseCodeValue commented on src/api/todo.ts
> +  return todos.map(todo => {
삼항 연산자 부분은 생각은 했었는데 지난 56개의 PR에서 가독성이 떨어진다는 리뷰를 받아서 사용하지 않았습니다!
저도 상당히 편하다고 생각하는데 아쉽더라구용

2021-09-10 07:34 UTC, SenseCodeValue commented on src/test/api/todo.test.ts
> +    const todo = createTodo('정대윤');
@hy57in 네 맞습니당

2021-09-10 07:34 UTC, SenseCodeValue commented on src/api/todo.ts
> +};
그것 까지는 진행 못했어용 ㅠㅠ

2021-09-10 07:46 UTC, SenseCodeValue commented on src/api/todo.ts
> +  return todos.map(todo => {
해당 직접 파라미터를 고치는 부분은 느낌적으로만 알고 있었는데 이번에 확실해 알게 되었어요 감사해용!
@Leehaeun0 

ps. 삼항연산 안쓰니까 펼치기 문법쓰면 코드가 너무 들어워져서 직접 접근으로 했는데 오히려 확실하게 알게되는게기가 되었습니당!!!

2021-09-10 08:13 UTC, SenseCodeValue commented on src/api/todo.ts
> +  return todos.map(todo => {
@Leehaeun0 해결~

2021-09-10 09:02 UTC, SenseCodeValue commented on src/test/api/todo.test.ts
> +    const todo = createTodo('정대윤');
해결~

2021-09-10 09:02 UTC, merged